name: bytebank
description: A new Bytebank project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  http:
  http_interceptor:
  uuid:
  intl: ^0.17.0
  cupertino_icons: ^0.1.2
  flutter_bloc: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/bytebank_logo.png